// <auto-generated />
using System;
using EntityFramworkFirstApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFramworkFirstApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210928090738_StudentIdentAdded")]
    partial class StudentIdentAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFramworkFirstApp.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SectionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SectionRecords");
                });

            modelBuilder.Entity("EntityFramworkFirstApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentSectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentSectionId");

                    b.ToTable("StudentRecords");
                });

            modelBuilder.Entity("EntityFramworkFirstApp.Models.Student", b =>
                {
                    b.HasOne("EntityFramworkFirstApp.Models.Section", "StudentSection")
                        .WithMany()
                        .HasForeignKey("StudentSectionId");

                    b.Navigation("StudentSection");
                });
#pragma warning restore 612, 618
        }
    }
}
